// Фронтальные изображения
export const manFrontMuscleGroupParts = {
	bicepsFull: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_biceps_full.png'),
	extensorCarp1Radials: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_extensor_carpi_radials.png'),
	// extensorCarp1Uharis: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_extensor_carp1_uharis.png'),
	// extensorDigitorum: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_extensor_digitorum.png'),
	// externalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_external_oblique.png'),
	forearmFull: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_forearm_full.png'),
	// frontDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_front_deltoid.png'),
	// gastrocnemius: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_gastrocnemius.png'),
	// gluteusMedius: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_gluteus_medius.png'),
	// internalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_internal_oblique.png'),
	// longBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_long_biceps.png'),
	// lowerAbs: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_lower_abs.png'),
	lowerLegFull: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_lower_leg_full.png'),
	// lowerMiddleAbs: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_lower_middle_abs.png'),
	// middleDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_middle_deltoid.png'),
	// pectoralisMajor: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_pectoralis_major.png'),
	// pectoralisMinor: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_pectoralis_minor.png'),
	pressFull: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_press_full.png'),
	rectoralFull: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_rectoral_full.png'),
	// scalenes: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_scalenes.png'),
	// serratusAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_serratus_anterior.png'),
	// shortBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_short_biceps.png'),
	// tibialisAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_tibialis_anterior.png'),
	// transversusAbdominis: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_transversus_abdominis.png'),
	// upperAbs: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_upper_abs.png'),
	upperLegFull: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_upper_leg_full.png'),
	// upperMiddleAbs: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_upper_middle_abs.png'),
	// upperTrapezius: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_upper_trapezius.png'),
	// vastusInternedius: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_vastus_internedius.png'),
	// vastusLateralis: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_vastus_lateralis.png'),
	// vastusMedialis: require('@/assets/muscle-selection-icons/man-front-muscle-group-parts/man_front_vastus_medialis.png'),
}

export const manFrontMuscleGroups = {
	bicepsFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_biceps_full.png'),
	// deltoidFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_deltoid_full.png'),
	// extensorCarpiRadials: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_extensor_carpi_radials.png'),
	// extensorCarpiUharis: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_extensor_carpi_uharis.png'),
	// extensorDigitorum: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_extensor_digitorum.png'),
	// externalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_external_oblique.png'),
	// forearmFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_forearm_full.png'),
	// frontDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_front_deltoid.png'),
	// gastrocnemius: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_gastrocnemius.png'),
	// gluteusMedius: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_gluteus_medius.png'),
	// internalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_internal_oblique.png'),
	// longBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_long_biceps.png'),
	// lowerAbs: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_lower_abs.png'),
	// lowerLegFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_lower_leg_full.png'),
	// lowerMiddleAbs: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_lower_middle_abs.png'),
	// middleDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_middle_deltoid.png'),
	// pectoralisMajor: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_pectoralis_major.png'),
	// pectoralisMinor: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_pectoralis_minor.png'),
	// pressFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_press_full.png'),
	// rectoralFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_rectoral_full.png'),
	// scalenes: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_scalenes.png'),
	// serratusAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_serratus_anterior.png'),
	// shortBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_short_biceps.png'),
	// tibialisAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_tibialis_anterior.png'),
	// transversusAbdominis: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_transversus_abdominis.png'),
	// upperAbs: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_upper_abs.png'),
	// upperLegFull: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_upper_leg_full.png'),
	// upperMiddleAbs: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_upper_middle_abs.png'),
	// upperTrapezius: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_upper_trapezius.png'),
	// vastusInternedius: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_vastus_internedius.png'),
	// vastusLateralis: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_vastus_lateralis.png'),
	// vastusMedialis: require('@/assets/muscle-selection-icons/man-front-muscle-groups/man_front_vastus_medialis.png'),
}

export const manFrontMuscleParts = {
	background: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_background.png'),
	// Left side
	leftExtensorCarpiRadialis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_extensor_carpi_radialis.png'),
	leftExtensorCarpiUharis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_extensor_carpi_ulnaris.png'),
	leftExtensorDigitorum: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_extensor_digitorum.png'),
	leftExternalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_external_oblique.png'),
	leftFrontDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_front_deltoid.png'),
	leftGastrocnemius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_gastrocnemius.png'),
	leftGluteusMedius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_gluteus_medius.png'),
	leftInternalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_internal_oblique.png'),
	leftLongBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_long_biceps.png'),
	leftMiddleDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_middle_deltoid.png'),
	leftPectoralisMajor: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_pectoralis_major.png'),
	leftPectoralisMinor: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_pectoralis_minor.png'),
	leftScalenes: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_scalenes.png'),
	leftSerratusAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_serratus_anterior.png'),
	leftShortBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_short_biceps.png'),
	leftTibialisAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_tibialis_anterior.png'),
	leftTransversusAbdominis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_transversus_abdominis.png'),
	leftUpperTrapezius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_upper_trapezius.png'),
	leftVastusInternedius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_vastus_intermedius.png'),
	leftVastusLateralis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_vastus_lateralis.png'),
	leftVastusMedialis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_left_vastus_medialis.png'),

	// Right side
	rightExtensorCarpiRadialis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_extensor_carpi_radialis.png'),
	rightExtensorCarpiUharis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_extensor_carpi_ulnaris.png'),
	rightExtensorDigitorum: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_extensor_digitorum.png'),
	rightExternalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_external_oblique.png'),
	rightFrontDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_front_deltoid.png'),
	rightGastrocnemius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_gastrocnemius.png'),
	rightGluteusMedius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_gluteus_medius.png'),
	rightInternalOblique: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_internal_oblique.png'),
	rightLongBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_long_biceps.png'),
	rightMiddleDeltoid: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_middle_deltoid.png'),
	rightPectoralisMajor: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_pectoralis_major.png'),
	rightPectoralisMinor: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_pectoralis_minor.png'),
	rightScalenes: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_scalenes.png'),
	rightSerratusAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_serratus_anterior.png'),
	rightShortBiceps: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_short_biceps.png'),
	rightTibialisAnterior: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_tibialis_anterior.png'),
	rightTransversusAbdominis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_transversus_abdominis.png'),
	rightUpperTrapezius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_upper_trapezius.png'),
	rightVastusInternedius: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_vastus_intermedius.png'),
	rightVastusLateralis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_vastus_lateralis.png'),
	rightVastusMedialis: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_right_vastus_medialis.png'),

	// Abs
	lowerAbs: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_lower_abs.png'),
	lowerMiddleAbs: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_lower_middle_abs.png'),
	upperAbs: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_upper_abs.png'),
	upperMiddleAbs: require('@/assets/muscle-selection-icons/man-front-muscle-parts/man_front_upper_middle_abs.png'),
}

// Задние изображения
export const manBackMuscleParts = {
	background: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_background.png'),

	// Left side
	// leftBtecosFemoris: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_btecos_femoris.png'),
	// leftFlexorDigitorumProfundus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_flexor_digitorum_profundus.png'),
	// leftFlexorPoliticsLongus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_flexor_politics_longus.png'),
	// leftGastrocnemius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_gastrocnemius.png'),
	// leftGluteusMaximus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_gluteus_maximus.png'),
	// leftGluteusMedius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_gluteus_medius.png'),
	// leftInternalColique: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_internal_colique.png'),
	// leftIntraspinatus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_intraspinatus.png'),
	// leftLatissimusDoris: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_latissimus_doris.png'),
	// leftLowerTrapezius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_lower_trapezius.png'),
	// leftRearDeltoid: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_rear_deltoid.png'),
	// leftSemitendinosus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_semitendinosus.png'),
	// leftThoracolumbarFascia: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_thoracolumbar_fascia.png'),
	// leftTriceps: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_triceps.png'),
	// leftUpperTrapezius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_left_upper_trapezius.png'),

	// // Right side
	// rightBtecosFemoris: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_btecos_femoris.png'),
	// rightFlexorDigitorumProfundus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_flexor_digitorum_profundus.png'),
	// rightFlexorPoliticsLongus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_flexor_politics_longus.png'),
	// rightGastrocnemius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_gastrocnemius.png'),
	// rightGluteusMaximus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_gluteus_maximus.png'),
	// rightGluteusMedius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_gluteus_medius.png'),
	// rightInternalColique: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_internal_colique.png'),
	// rightIntraspinatus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_intraspinatus.png'),
	// rightLatissimusDoris: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_latissimus_doris.png'),
	// rightLowerTrapezius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_lower_trapezius.png'),
	// rightRearDeltoid: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_rear_deltoid.png'),
	// rightSemitendinosus: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_semitendinosus.png'),
	// rightThoracolumbarFascia: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_thoracolumbar_fascia.png'),
	// rightTriceps: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_triceps.png'),
	// rightUpperTrapezius: require('@/assets/muscle-selection-icons/man-back-muscle-parts/man_back_right_upper_trapezius.png'),
}

export const manBackMuscleGroups = {
	// bicecsFemoris: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_bicecs_femoris.png'),
	// buttFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_butt_full.png'),
	// detroidFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_detroid_full.png'),
	// flexorDrgtorumProfundus: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_flexor_drgtorum_profundus.png'),
	// flexorPoliticsLongus: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_flexor_politics_longus.png'),
	// forearmFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_forearm_full.png'),
	// clulteusMaximus: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_clulteus_maximus.png'),
	// clulteusMedius: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_clulteus_medius.png'),
	// internalDblique: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_internal_dblique.png'),
	// intraspindrus: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_intraspindrus.png'),
	// latissimusDorsi: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_latissimus_dorsi.png'),
	// lowerLegFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_lower_leg_full.png'),
	// semitendinosus: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_semitendinosus.png'),
	// spineFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_spine_full.png'),
	// thoracolumbarFascia: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_thoracolumbar_fascia.png'),
	// trapeziusFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_trapezius_full.png'),
	// triceps: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_triceps.png'),
	// upperLegFull: require('@/assets/muscle-selection-icons/man.back_muscle_groups/man_back_upper_leg_full.png'),
}

export const manBackMuscleGroupParts = {
	// bicacsFemoris: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_bicacs_femoris.png'),
	// buttFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_butt_full.png'),
	// detroidFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_detroid_full.png'),
	// flexorDigtorumProfundus: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_flexor_digtorum_profundus.png'),
	// flexorPollicisLongus: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_flexor_pollicis_longus.png'),
	// forearmFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_forearm_full.png'),
	// gluteusMaximus: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_gluteus_maximus.png'),
	// gluteusMedius: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_gluteus_medius.png'),
	// internalOblique: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_internal_oblique.png'),
	// intraspinatus: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_intraspinatus.png'),
	// latissimusDorsi: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_latissimus_dorsi.png'),
	// lowerLegFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_lower_leg_full.png'),
	// semifendinosus: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_semifendinosus.png'),
	// spineFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_spine_full.png'),
	// thoracolumbarFascia: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_thoracolumbar_fascia.png'),
	// trapeziusFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_trapezius_full.png'),
	// triceps: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_triceps.png'),
	// upperLegFull: require('@/assets/muscle-selection-icons/man.back_muscle_group_parts/man_back_upper_leg_full.png'),
}

// Общий экспорт всех изображений
export const allImages = {
	...manFrontMuscleGroupParts,
	...manFrontMuscleGroups,
	...manFrontMuscleParts,
	...manBackMuscleParts,
	...manBackMuscleGroups,
	...manBackMuscleGroupParts,
}

// Экспорт по умолчанию всех объектов
export default {
	manFrontMuscleGroupParts,
	manFrontMuscleGroups,
	manFrontMuscleParts,
	manBackMuscleParts,
	manBackMuscleGroups,
	manBackMuscleGroupParts,
	allImages,
}
